### ISSUE TITLE
Import search path

### ISSUE THREAD

**Issue by mhfrantz** [EvgSkv/logica#132]
In version `1.3.14`, the `import` resolves relative to the current directory. We are trying to deploy Logica files embedded with our Python package, so they can be anywhere on `sys.path`. Would it be possible to change the parser so that a list of directories (like `sys.path`) could be provided for resolving `import`?

**Comment by EvgSkv** [comment]
Certainly we need an ability to run programs from a folder other than current. I've added `import_root` argument letting you specify a root other than current folder:
https://github.com/EvgSkv/logica/pull/135/files
Does that cover the needs of your project?

You mentioned searching in a list of folders and I am not immediately certain what would be reasonable limitations for this search. Generally I'd be worried some user creates a file with a common name, like `util.l`, in two folders and then has a nightmare debugging trying to understand why results are not as they expected, or why is the predicate not found.
I know this overall approached is used in other languages, e.g. Python, but it's probably organized more subtly than just trying to find file in all of the folders, I'm not sure...

So if one root solves your problem we can stop at it.
Otherwise let me know, we'll figure out the solution.

**Comment by mhfrantz** [comment]
Our situation is that we have multiple Python repos, and we want to put `*.l` files in each one alongside the `*.py` files. While we're developing in one repo, we'd like to be able to import from any of the repos. We might have some of the repos installed in one location (e.g. `pip install`) while others are available in another (e.g. from source).

We would always use fully qualified hierarchical names to disambiguate, so instead of `import util`, it would be more like `import acme.foo.util` and `import acme.bar.util`. It is very analogous to how Python imports work. In fact, we would be using `sys.path` as the list of root directories that we'd like Logica to search. The "first match" approach would probably be familiar to most users, although I can appreciate how the complexity might lead to some confusing corner cases.

**Comment by EvgSkv** [comment]
Got it!
Are you calling the parser from Python, so support for paths there would suffice? Or you need the command line tool to accept it somehow as well?

**Comment by EvgSkv** [comment]
PR merged, pypi packaged pushed: https://pypi.org/project/logica/1.3.14.15.92/.
