### ISSUE TITLE
Addressing issues of SQL

### ISSUE THREAD

**Issue by x4m** [EvgSkv/logica#7]
Hi Evgeny!
I'm a little bit involved into PostgreSQL development, so I decided to take a look on Logica.
Seems like an interesting piece of research, thanks!

There is a good post summarizing developers complains about SQL [0]. How do you think, does Logica address these issues?
Here's the list of SQL problems:
    lack of proper orthogonality — SQL is hard to compose;
    lack of compactness — SQL is a large language;
    lack of consistency — SQL is inconsistent in syntax and semantics;
    poor system cohesion — SQL does not integrate well enough with application languages and protocols.

Thanks!

[0] https://www.edgedb.com/blog/we-can-do-better-than-sql/

**Comment by EvgSkv** [comment]
Hello Andrey,
thanks for reaching out!

This post is indeed an interesting summary.  Here is how I believe Logica is addressing the issues the authors raised.

1. _SQL is hard to compose._

Consider and example from the article:

```
SELECT name
FROM emp
WHERE role = 'dept head'
```

Authors point out that the method of re-using this query is different depending on whether it returns one or more rows per department. Here is how this query and it's use would be done in Logica. I will use a full names for the table fields for better readability.

```
# Calculating department heads from `emp` table.
Head(deptno) = department_head :-
  `emp`(deptno:, role: "dept head", name: department_head);

# Using DepartmentHead predicate to along with other department information.
DepartmentInfo(name:, location:, head: Head(no)) :-
  `dept`(no:, location:, name:);
```

This code would work whether each department has exactly one head or more than one.

Here we were able to use _functional notation_ since `Head` predicate extracts only one field. Otherwise we could use a regular predicate call to extract multiple columns, and it would also be used the same way whether it extracts one or more than one row.

2. _SQL language is large._

Logica is small, it only has four reserved words `if`, `then`, `else`, `in`, definition symbols `:-`, `:=`, propositional operators and built-in functions. It is small because it leverages syntax of predicate calculus, which mathematicians were perfecting for a very long time [0].

But I should acknowledge that:

* The work of translating the SQL function arsenal into Logica is not complete, some SQL functions can only be addressed via `SqlExpr` Logica function, which takes raw SQL as an input. Yet I think this is more of an exception in the normal workflow of Logica users.

* Formal human-readable syntax definition of Logica is yet to be written, currently it is taught via examples. I do believe it will be quite short though.

3. _SQL is inconsistent in syntax and semantics._

Similarly to point (2), since Logica is founded on predicate calculus it inherits consistency of syntax and semantics.

It's worth noting that partially SQL is a victim of its own success here: many systems chose to use SQL for its language and not all were consistent with each other.

I hope that Logica will address this in the long term. Now there is a basic support of a user to chose whether their Logica program to compile to run on BigQuery, PostgreSQL and SQLite. For example program `greet.l`

```
@DefineFlag("engine", "bigquery");
@Engine(FlagValue("engine"));
Greet("hello" ++ " " ++ entity) :- entity == "world" | entity == "earth"
```

will run on any of these engines depending on the command line flag `engine` that user choses to provide. For instance

```
$ logica - run_to_csv Greet --engine=sqlite 
col0
"hello world"
"hello earth"
```
runs on SQLite.

Yet we do face the challenge that the core functionality supported by these systems could be different. For instance SQLite does not support arrays, which make lists unusable in Logica if user choses SQLite as back-end. Almost all of the work of addressing ecosystem inconsistencies is yet to be done.

4. SQL does not integrate well enough with application languages and protocols.

I am not sure if I agree with this broad statement. While working on Logica I found it easy to call SQL from Python, and in my work with SQL I found integration with many systems to be very good.

The authors give a specific example of outputting structures, which indeed many SQL-driven systems (e.g. SQLite and MySQL) don't support. Yet for instance BigQuery supports structures and Logica can leverage this functionality to support structures as well. 

```
Movie(
    name: "Terminator 2",
    characters: ["Sarah Connor", "John Connor", "Terminator"],
    reviews: [{title: "Great movie", author: "John Doe"}, {title: "Best movie!", author: "Jane Doe"}]);
```

Thanks again for your question.

[0] https://en.wikipedia.org/wiki/History_of_logic

**Comment by x4m** [comment]
Just as side note: I'm not sure using backticks and double quotes together is a good thing to keeping learning curve smooth. Those who do not use command prompt (~ most of Windows devs) never heard about backticks.

About integration of SQL into procedural languages - it's a plot of so many memes.
For example look for "lasagna code": embedding program into program. It's a classical source of bugs and vulnerabilities.
String literals in code are not checked against SQL type system, are not managed by git, are not versioned for different database schema versions etc etc.
Many databases have non-atomic values: structs, tuples, records, documents, jsons. E.g. PostgreSQL has all of them :) But SQL-92 interface is designed to return rows without nesting. That's the main source of so-called "Object-relational impedance": relational algebra maps poorly to object-oriented world. Luckily, OO is somewhat out of favor in development world :)
One of a good attempts to  tackle ORI is LINQ - part of C# specs that translates into queries, it is managed by VCS of parent project, checked against both type system(of a client and of a server), manages schema migrations etc. Yet it's weak side is performance. Most of the time it operates well. But if you do not know how it translates your queries to guts of SQL - it can became bottleneck unexpectedly.
